#lang racket/base

(require "common.rkt" ffi/unsafe)
(provide (all-defined-out))

(define _tcod-list-t* (_cpointer 'TCOD_list_t))

(define-tcod tcod-list-new (_fun -> _tcod-list-t*) #:c-id TCOD_list_new)
(define-tcod tcod-list-allocate (_fun (nb-elements : _int) -> _tcod-list-t*) #:c-id TCOD_list_allocate)
(define-tcod tcod-list-duplicate (_fun _tcod-list-t* -> _tcod-list-t*) #:c-id TCOD_list_duplicate)
(define-tcod tcod-list-delete (_fun _tcod-list-t* -> _void) #:c-id TCOD_list_delete)
(define-tcod tcod-list-push (_fun _tcod-list-t* (element : _void*) -> _void) #:c-id TCOD_list_push)
(define-tcod tcod-list-pop (_fun _tcod-list-t* -> _void*) #:c-id TCOD_list_pop)
(define-tcod tcod-list-peek (_fun _tcod-list-t* -> _void*) #:c-id TCOD_list_peek)
(define-tcod tcod-list-add-all (_fun _tcod-list-t* _tcod-list-t* -> _void) #:c-id TCOD_list_add_all)
(define-tcod tcod-list-get (_fun _tcod-list-t* (index : _int) -> _void*) #:c-id TCOD_list_get)
(define-tcod tcod-list-set (_fun _tcod-list-t* *(element : _void*) (index : _int) -> _void) #:c-id TCOD_list_set)
(define-tcod tcod-list-begin (_fun _tcod-list-t* -> _void*) #:c-id TCOD_list_begin)
(define-tcod tcod-list-end (_fun _tcod-list-t* -> _void*) #:c-id TCOD_list_end)
(define-tcod tcod-list-reverse (_fun _tcod-list-t* -> _void) #:c-id TCOD_list_reverse)
(define-tcod tcod-list-remove-iterator (_fun _tcod-list-t* (element : _void*) -> _void*) #:c-id TCOD_list_remove_iterator)
(define-tcod tcod-list-remove (_fun _tcod-list-t* (element : _void*) -> _void) #:c-id TCOD_list_remove)
(define-tcod tcod-list-remove-iterator-fast (_fun _tcod-list-t* (element : _void*) -> _void*) #:c-id TCOD_list_remove_iterator_fast)
(define-tcod tcod-list-remove-fast (_fun _tcod-list-t* (element : _void*) -> _void) #:c-id TCOD_list_remove_fast)
(define-tcod tcod-list-contains (_fun _tcod-list-t* (element : _void*) -> _bool) #:c-id TCOD_list_contains)
(define-tcod tcod-list-clear (_fun _tcod-list-t* -> _void) #:c-id TCOD_list_clear)
(define-tcod tcod-list-clear_and_delete (_fun _tcod-list-t* -> _void) #:c-id TCOD_list_clear_and_delete)
(define-tcod tcod-list-size (_fun _tcod-list-t* -> _int) #:c-id TCOD_list_size)
(define-tcod tcod-list-insert-before (_fun _tcod-list-t* (element : _void*) (before : _int) -> _void*) #:c-id TCOD_list_insert_before)
(define-tcod tcod-list-is-empty (_fun _tcod-list-t* -> _bool) #:c-id TCOD_list_is_empty)
