#lang racket/base

(require "common.rkt" ffi/unsafe)
(provide (all-defined-out))

(define _TCOD_list_t* (_cpointer _void))

(define-tcod TCOD_list_new (_fun -> _TCOD_list_t*))
(define-tcod TCOD_list_allocate (_fun _int -> _TCOD_list_t*))
(define-tcod TCOD_list_duplicate (_fun _TCOD_list_t* -> _TCOD_list_t*))
(define-tcod TCOD_list_delete (_fun _TCOD_list_t* -> _void))
(define-tcod TCOD_list_push (_fun _TCOD_list_t* _cpointer -> _cpointer))
(define-tcod TCOD_list_pop (_fun _TCOD_list_t* -> _cpointer))
(define-tcod TCOD_list_peek (_fun _TCOD_list_t* -> _cpointer))
(define-tcod TCOD_list_add_all (_fun _TCOD_list_t* _TCOD_list_t* -> _void))
(define-tcod TCOD_list_get (_fun _TCOD_list_t* _int -> _cpointer))
(define-tcod TCOD_list_set (_fun _TCOD_list_t* _cpointer _int -> _void))
(define-tcod TCOD_list_begin (_fun _TCOD_list_t* -> _cpointer))
(define-tcod TCOD_list_end (_fun _TCOD_list_t* -> _cpointer))
(define-tcod TCOD_list_reverse (_fun _TCOD_list_t* -> _void))
(define-tcod TCOD_list_remove_iterator (_fun _TCOD_list_t* _cpointer -> _cpointer))
(define-tcod TCOD_list_remove (_fun _TCOD_list_t* _cpointer -> _void))
(define-tcod TCOD_list_remove_iterator_fast (_fun _TCOD_list_t* _cpointer -> _cpointer))
(define-tcod TCOD_list_remove_fast (_fun _TCOD_list_t* _cpointer -> _void))
(define-tcod TCOD_list_contains (_fun _TCOD_list_t* _cpointer -> _bool))
(define-tcod TCOD_list_clear (_fun _TCOD_list_t* -> _void))
(define-tcod TCOD_list_clear_and_delete (_fun _TCOD_list_t* -> _void))
(define-tcod TCOD_list_size (_fun _TCOD_list_t* -> _int))
(define-tcod TCOD_list_insert_before (_fun _TCOD_list_t* _cpointer _int -> _cpointer))
(define-tcod TCOD_list_is_empty (_fun _TCOD_list_t* -> _bool))
